name: 'klaviyo'
profile: 'databricks' 
version: '0.9.0'
config-version: 2
require-dbt-version: [">=1.3.0", "<2.0.0"]

model-paths: ["models"]
packages-install-path: "dbt_packages"

vars:
  klaviyo_database: 0006_wsg       # Your Databricks catalog
  klaviyo_schema: stg_klaviyo             # The schema created by dbt_klaviyo_source

  klaviyo__email_attribution_lookback: 120
  klaviyo__sms_attribution_lookback: 24

  klaviyo__eligible_attribution_events:
    - 'opened email'
    - 'clicked email'
    - 'clicked sms'

  klaviyo__count_metrics:
    - 'Active on Site'
    - 'Viewed Product'
    - 'Ordered Product'
    - 'Placed Order'
    - 'Refunded Order'
    - 'Received Email'
    - 'Clicked Email'
    - 'Opened Email'
    - 'Marked Email as Spam'
    - 'Unsubscribed'
    - 'Received SMS'
    - 'Clicked SMS'
    - 'Sent SMS'
    - 'Unsubscribed from SMS'

  klaviyo__sum_revenue_metrics:
    - 'Refunded Order'
    - 'Placed Order'
    - 'Ordered Product'
    - 'checkout started'
    - 'cancelled order'

  klaviyo__event_pass_through_columns: []
  klaviyo__person_pass_through_columns: []

dispatch:
  - macro_namespace: dbt_utils
    search_order: ['spark_utils', 'dbt_utils']

models:
  +materialized: table
  klaviyo:
    +schema: fct_klaviyo                  # This is where final models will be saved
