name: 'klaviyo'
profile: 'databricks'
version: '0.9.0'
config-version: 2
require-dbt-version: [">=1.3.0", "<2.0.0"]

dispatch:
  - macro_namespace: dbt_utils
    search_order: ['spark_utils', 'dbt_utils']

vars:
  klaviyo_database: 0006_wsg
  klaviyo_schema: default_stg_klaviyo

  # new-style
  event: "{{ ref('stg_klaviyo__event') }}"
  person: "{{ ref('stg_klaviyo__person') }}"
  campaign: "{{ ref('stg_klaviyo__campaign') }}"
  flow: "{{ ref('stg_klaviyo__flow') }}"
  metric: "{{ ref('stg_klaviyo__metric') }}"
  integration: "{{ ref('stg_klaviyo__integration') }}"

  # old-style (back-compat)
  event_table: "{{ ref('stg_klaviyo__event') }}"
  person_table: "{{ ref('stg_klaviyo__person') }}"
  campaign_table: "{{ ref('stg_klaviyo__campaign') }}"
  flow_table: "{{ ref('stg_klaviyo__flow') }}"
  metric_table: "{{ ref('stg_klaviyo__metric') }}"
  integration_table: "{{ ref('stg_klaviyo__integration') }}"


  klaviyo__email_attribution_lookback: 120
  klaviyo__sms_attribution_lookback: 24

  klaviyo__eligible_attribution_events:
    - 'opened email'
    - 'clicked email'
    - 'clicked sms'

  klaviyo__count_metrics:
    - 'Active on Site'
    - 'Viewed Product'
    - 'Ordered Product'
    - 'Placed Order'
    - 'Refunded Order'
    - 'Received Email'
    - 'Clicked Email'
    - 'Opened Email'
    - 'Marked Email as Spam'
    - 'Unsubscribed'
    - 'Received SMS'
    - 'Clicked SMS'
    - 'Sent SMS'
    - 'Unsubscribed from SMS'

  klaviyo__sum_revenue_metrics:
    - 'Refunded Order'
    - 'Placed Order'
    - 'Ordered Product'
    - 'checkout started'
    - 'cancelled order'

  klaviyo__event_pass_through_columns: []
  klaviyo__person_pass_through_columns: []

model-paths: ["models"]
packages-install-path: "dbt_packages"

models:
  +materialized: table
  klaviyo:
    +schema: fct_klaviyo
